# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.0-SNAPSHOT
maven_group=com.ingotcraft
archives_name=create-italian-industries
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
# Dependencies
architectury_api_version=13.0.11
fabric_loader_version=0.19.5
fabric_api_version=0.116.17+1.21.1
neoforge_version=21.1.252
# NeoForge Dependencies (Create)
nf_create_version=6.0.10-280
nf_ponder_version=1.0.82
nf_flywheel_version=1.0.6
nf_registrate_version=MC1.21-1.3.0+67
